# application.yml
server:
  port: 7500
  ssl:
    key-store:
    key-store-password:
    key-store-type:

# Spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9b204.p.ssafy.io:50000/talktopia?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username:
    password:



  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      # (create / create-drop / update / validate)

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.MySQL57Dialect # 채팅 시간을 Datetime(3)으로 넣기 위함

  # JWT
  security:
    jwt:
      secret:

  #redis
  redis:
    host: talktopia.site
    port: 6379
    password :
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1

  # 레디스 캐싱
  cache:
    type: redis

# log level
logging:
  level:
    root: INFO
